[pytest]
addopts = -s -v --alluredir=./allure-results
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Маркировка для smoke тестов.
    regression: Маркировка для регрессионных тестов.
    functional: Маркировка для функциональных тестов.
    navigation: Маркировка для тестов навигации.
    view: Маркировка для тестов внешнего вида.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    courses: Маркировка для тестов, связанных с курсами пользователей.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.
    failed_function: Маркировка для умышленно падающих тестов и фикстур со скоупом function, предназначенных для демонстрации отчета.
    failed_session: Маркировка для умышленно падающих фикстур со скоупом session, предназначенных для демонстрации отчета (запускать отдельно).
    failed_class: Маркировка для умышленно падающих фикстур со скоупом class, предназначенных для демонстрации отчета.
    failed_module: Маркировка для умышленно падающих фикстур со скоупом module, предназначенных для демонстрации отчета (запускать отдельно).
    fixed_function: Маркировка для тестов с исправленными багами, но со ссылками на них, предназначенных для демонстрации отчета.